### ISSUE TITLE
build error: "jetbrainser/src/app" src\app\init.go:14:12: pattern resources_enc: no matching files found

### ISSUE THREAD

**Issue by junkloader** [p1ratrulezzz/brainser#14]
master branch fails to build due to missing embed resource:

go build -tags console -o "bin/jetbrainser-win-x64.exe" "jetbrainser/src/app"
src\app\init.go:14:12: pattern resources_enc: no matching files found

Can't seem to find this resource anywhere in the current head of the repo.

**Comment by p1ratrulezzz** [comment]
Resources must be downloaded separately, it is not to be included here in repo

**Comment by junkloader** [comment]
Can you kindly provide a location to where I might find these resources?
