### ISSUE TITLE
Cannot use zip and cannot compile from source

### ISSUE THREAD

**Issue by davidbitterlich** [p1ratrulezzz/brainser#15]
Hi,

unfortunatelly I am unable to extract the release zips provided on the release page as they are password protected and there is no information about the password to decompress.

Also I cannot build the tool from source as something is missing there (like in issue #14  where the only information is "Resources must be downloaded separately, it is not to be included here in repo", but from where?)

I would really appreciate to use your tool, but am currently unable to do so.

**Comment by japodhidev** [comment]
I second this. I also resorted to trying to building from source since the releases are password protected. I however managed to build three (`linux-arm64`, `linux-amd64` & `windows-amd64`) but one target (`darwin-amd64`) failed to build. However I run into an issue trying to patch the new products (v2022.3). Here's a terminal output I got while running the GUI version (`linux-amd64`):

```sh
2023/01/28 12:18:16 Fyne error:  Error getting current data value
2023/01/28 12:18:16   Cause: index out of bounds
2023/01/28 12:18:16   At: fyne.io/fyne/v2@v2.2.4/widget/label.go:146
2023/01/28 12:18:16 Fyne error:  Error getting current data value
2023/01/28 12:18:16   Cause: index out of bounds
2023/01/28 12:18:16   At: fyne.io/fyne/v2@v2.2.4/widget/label.go:146
panic: encrypted data is empty

goroutine 8 [running]:
jetbrainser/src/cryptor.Decrypt({0x0, 0x0, 0x0})
    jetbrainser/src/cryptor/crypt.go:32 +0x111
main.getResource({0xa70bb7?, 0x9?})
    jetbrainser/src/app/helpers.go:59 +0xb2
main.checkAgentExists({0x0, 0x0, 0xb81460?})
    jetbrainser/src/app/helpers.go:126 +0x33
main.doPatch({0xc000276b70, 0x26}, {0x0, 0x0}, {0x0, 0x0}, 0x9)
    jetbrainser/src/app/patch.go:48 +0x392
main.gui.func3()
    jetbrainser/src/app/gui.go:109 +0x529
fyne.io/fyne/v2/widget.(*Button).Tapped(0xc000370780, 0xc0000b0001)
    fyne.io/fyne/v2@v2.2.4/widget/button.go:194 +0x53
fyne.io/fyne/v2/internal/driver/glfw.(*window).mouseClickedHandleTapDoubleTap.func1()
    fyne.io/fyne/v2@v2.2.4/internal/driver/glfw/window.go:634 +0x26
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x0?)
    fyne.io/fyne/v2@v2.2.4/internal/driver/common/window.go:35 +0x3e
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
    fyne.io/fyne/v2@v2.2.4/internal/driver/glfw/window.go:942 +0x136
```

Thanks a lot for providing this tool. I've been using it with `v2022.2` products for quite some time now.
