### ISSUE TITLE
Themida protection?

### ISSUE THREAD

**Issue by McSkinnerOG** [p1ratrulezzz/brainser#23]
Why on earth is this using Themida? There is ZERO reason i should have to uninstall system monitoring tools to use this... Seems sus af

**Comment by p1ratrulezzz** [comment]
It is only for windows x64 binary, other binaries are provided as is. Also
you can compile it from sources by yourself, the compiled binary will not
be protected by themida

ср, 26 июл. 2023 г. в 05:49, Va1idUser ***@***.***>:
