### ISSUE TITLE
Program doesn't work with 2022.2 

### ISSUE THREAD

**Issue by kremlev404** [p1ratrulezzz/brainser#6]
Hi, i got this kind of error in clion 
Cannot obtain ticket from http://127.0.0.1:1337 due to connectivity problem: Connection refused
It happend only with 2022.2
In 2021.1.3 everything is fine.
System: Ubuntu 20.04 on VMWare.

**Comment by p1ratrulezzz** [comment]
Fixed in new version. Will upload it soon
